@echo off
REM ============================================================
REM ARKON Full Build Pipeline
REM Builds everything: frontend, backend, bundles, and installer
REM ============================================================

setlocal enabledelayedexpansion

set PROJECT_ROOT=%~dp0..
set SCRIPTS_DIR=%~dp0

echo.
echo ============================================================
echo  ARKON Build Pipeline v1.0.0
echo ============================================================
echo.
echo  Steps:
echo    1. Build Frontend (Vite + React)
echo    2. Build Backend (PyInstaller)
echo    3. Bundle Python Runtime
echo    4. Bundle Resources
echo    5. Bundle Plugins
echo    6. Bundle Workers
echo    7. Build Tauri App
echo    8. Generate Installer
echo    9. Generate Portable Version
echo.
echo ============================================================
echo.

REM Step 1: Build Frontend
echo [STEP 1/9] Building Frontend...
call "%SCRIPTS_DIR%\build-frontend.bat"
if errorlevel 1 (
    echo ERROR: Frontend build failed!
    exit /b 1
)
echo.

REM Step 2: Build Backend
echo [STEP 2/9] Building Backend...
call "%SCRIPTS_DIR%\build-backend.bat"
if errorlevel 1 (
    echo ERROR: Backend build failed!
    exit /b 1
)
echo.

REM Step 3: Bundle Python Runtime
echo [STEP 3/9] Bundling Python Runtime...
call "%SCRIPTS_DIR%\bundle-python.bat"
if errorlevel 1 (
    echo ERROR: Python bundling failed!
    exit /b 1
)
echo.

REM Step 4: Bundle Resources
echo [STEP 4/9] Bundling Resources...
call "%SCRIPTS_DIR%\bundle-resources.bat"
if errorlevel 1 (
    echo ERROR: Resource bundling failed!
    exit /b 1
)
echo.

REM Step 5: Bundle Plugins
echo [STEP 5/9] Bundling Plugins...
call "%SCRIPTS_DIR%\bundle-plugins.bat"
if errorlevel 1 (
    echo ERROR: Plugin bundling failed!
    exit /b 1
)
echo.

REM Step 6: Bundle Workers
echo [STEP 6/9] Bundling Workers...
call "%SCRIPTS_DIR%\bundle-workers.bat"
if errorlevel 1 (
    echo ERROR: Worker bundling failed!
    exit /b 1
)
echo.

REM Step 7: Build Tauri App
echo [STEP 7/9] Building Tauri App...
cd "%PROJECT_ROOT%\apps\desktop"
call npx tauri build
if errorlevel 1 (
    echo ERROR: Tauri build failed!
    exit /b 1
)
echo.

REM Step 8: Generate Installer (already done by Tauri with NSIS target)
echo [STEP 8/9] Installer generated by Tauri build.
echo.

REM Step 9: Generate Portable Version
echo [STEP 9/9] Generating Portable Version...
call "%SCRIPTS_DIR%\package-portable.bat"
if errorlevel 1 (
    echo ERROR: Portable packaging failed!
    exit /b 1
)
echo.

echo ============================================================
echo  BUILD COMPLETE!
echo ============================================================
echo.
echo  Outputs:
echo    Installer:  apps\desktop\src-tauri\target\release\bundle\nsis\ARKON_Setup.exe
echo    Portable:   release\ARKON_Portable.zip
echo.
echo ============================================================
